/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JInternalFrame;
import javax.swing.plaf.InternalFrameUI;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Luis
 */
public class CrearHorario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearHorario
     */
    public CrearHorario() {
        initComponents();
        
        //Quitar la barra de titulo
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblAulaHorario = new javax.swing.JLabel();
        txtAulaHorario = new javax.swing.JTextField();
        lblCrearHorario = new javax.swing.JLabel();
        btnAgregarExp = new javax.swing.JButton();
        lblFolioHorario = new javax.swing.JLabel();
        btnAgregarExp1 = new javax.swing.JButton();
        txtFolioHorario = new javax.swing.JTextField();
        lblGrupoHorario = new javax.swing.JLabel();
        txtGrupoHorario = new javax.swing.JTextField();
        lblProgEdu = new javax.swing.JLabel();
        txtProgEdu = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Experiencia Educativa", "NRC", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblAulaHorario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblAulaHorario.setText("Aula:");

        txtAulaHorario.setEditable(false);
        txtAulaHorario.setBackground(new java.awt.Color(255, 255, 255));
        txtAulaHorario.setBorder(null);

        lblCrearHorario.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lblCrearHorario.setText("Crear horario");

        btnAgregarExp.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarExp.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnAgregarExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnAgregarExp.setText("Agregar Experiencia Educativa");
        btnAgregarExp.setActionCommand("  Agregar Experiencia Educativa");
        btnAgregarExp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAgregarExp.setBorderPainted(false);
        btnAgregarExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarExpMousePressed(evt);
            }
        });
        btnAgregarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExpActionPerformed(evt);
            }
        });

        lblFolioHorario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblFolioHorario.setText("Folio:");

        btnAgregarExp1.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarExp1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnAgregarExp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        btnAgregarExp1.setText("Eliminar Experiencia Educativa");
        btnAgregarExp1.setActionCommand("  Agregar Experiencia Educativa");
        btnAgregarExp1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAgregarExp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExp1ActionPerformed(evt);
            }
        });

        txtFolioHorario.setEditable(false);
        txtFolioHorario.setBackground(new java.awt.Color(255, 255, 255));
        txtFolioHorario.setBorder(null);

        lblGrupoHorario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblGrupoHorario.setText("Grupo:");

        txtGrupoHorario.setEditable(false);
        txtGrupoHorario.setBackground(new java.awt.Color(255, 255, 255));
        txtGrupoHorario.setBorder(null);

        lblProgEdu.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblProgEdu.setText("Programa Educativo:");

        txtProgEdu.setEditable(false);
        txtProgEdu.setBackground(new java.awt.Color(255, 255, 255));
        txtProgEdu.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFolioHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFolioHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGrupoHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGrupoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProgEdu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProgEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAulaHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAulaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCrearHorario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btnAgregarExp1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCrearHorario)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFolioHorario)
                    .addComponent(txtFolioHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupoHorario)
                    .addComponent(txtGrupoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgEdu)
                    .addComponent(txtProgEdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAulaHorario)
                    .addComponent(txtAulaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarExp1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarExpActionPerformed

    private void btnAgregarExp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarExp1ActionPerformed

    private void btnAgregarExpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarExpMousePressed
        
    }//GEN-LAST:event_btnAgregarExpMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarExp;
    private javax.swing.JButton btnAgregarExp1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAulaHorario;
    private javax.swing.JLabel lblCrearHorario;
    private javax.swing.JLabel lblFolioHorario;
    private javax.swing.JLabel lblGrupoHorario;
    private javax.swing.JLabel lblProgEdu;
    private javax.swing.JTextField txtAulaHorario;
    private javax.swing.JTextField txtFolioHorario;
    private javax.swing.JTextField txtGrupoHorario;
    private javax.swing.JTextField txtProgEdu;
    // End of variables declaration//GEN-END:variables
}
